import './globals.css'
import { RegisterPWA } from "./register";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <meta name="theme-color" content="#fff" />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/icon.png" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
          <link
              href="https://fonts.googleapis.com/css2?family=Noto+Sans+Georgian&family=Roboto+Mono&display=swap"
              rel="stylesheet"
          />
      </head>
      <body>
      {children}
      <RegisterPWA />
      </body>
    </html>
  )
}
