# Generated by Django 4.2.1 on 2023-05-25 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='88f6d892-8504-47c4-8661-ae7fd4e91341', max_length=50),
        ),
    ]
