# Generated by Django 4.2.1 on 2023-05-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country_user_last_login_user_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='65163639-49b0-4fb2-9af3-9a942b7e04b4', max_length=50),
        ),
    ]
